# Generated by Django 3.0.2 on 2020-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='metrics name')),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('date_registered', models.DateField()),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
